In [1]:
# import the data set and intital column heads 
# had to increase computing power to 256gb ram

import pandas as pd

# Load the final dataset for Knowledge Discovery
file = "merged_dataset_movement_5.csv"
df = pd.read_csv(file)

print("Rows:", len(df))
print("Columns:", len(df.columns))
df.head()

Rows: 34541051
Columns: 107

,YEAR,SERIAL,NUMPREC,NUMPERHH,STATEFIP,CITY,URBAN,GQ,SPLITHID,PERNUM,...,HISTID_MOM2,HISTID_POP2,STATEICP,COUNTYICP,COUNTYNHG,GQTYPE,GQTYPED,SICKNESS,LINK1850,MOVED
0,1860,1,6,6,1,0,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,1
1,1860,1,6,6,1,0,1,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
2,1860,1,6,6,1,0,1,1,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,1
3,1860,1,6,6,1,0,1,1,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
4,1860,3,8,8,1,0,1,1,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0

In [4]:
import pandas as pd
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline

# Load data
df = pd.read_csv("merged_dataset_movement_5.csv")

# Target
y = df["MOVED"]

# Features
X = df.drop(columns=["MOVED"])

# Identify categorical vs numeric
categorical_cols = X.select_dtypes(include=["object"]).columns
numeric_cols = X.select_dtypes(include=["int64", "float64"]).columns

# Preprocessing
preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse=False), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)


# Naive Bayes model
model = Pipeline(steps=[
    ("preprocess", preprocess),
    ("nb", GaussianNB())
])

# 10-fold CV
kf = KFold(n_splits=10, shuffle=True, random_state=42)

y_pred = cross_val_predict(model, X, y, cv=kf)

# Accuracy
accuracy = accuracy_score(y, y_pred)
print("10-fold CV Accuracy:", accuracy)

# Confusion matrix
cm = confusion_matrix(y, y_pred)
print("Confusion Matrix:")
print(cm)

MemoryError: Unable to allocate 13.3 PiB for an array with shape (31086945, 60034924) and data type float64

In [6]:
df.columns

Index(['YEAR', 'SERIAL', 'NUMPREC', 'NUMPERHH', 'STATEFIP', 'CITY', 'URBAN',
       'GQ', 'SPLITHID', 'PERNUM',
       ...
       'HISTID_MOM2', 'HISTID_POP2', 'STATEICP', 'COUNTYICP', 'COUNTYNHG',
       'GQTYPE', 'GQTYPED', 'SICKNESS', 'LINK1850', 'MOVED'],
      dtype='object', length=107)

In [7]:
X = df.drop(columns=["MOVED", "COUNTYICP", "OCC"])

In [8]:
from sklearn.preprocessing import OrdinalEncoder

preprocess = ColumnTransformer(
    transformers=[
        ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)

In [9]:
# to many catergorical variables are making dummy variables explode in number

import pandas as pd
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline

# Load data
df = pd.read_csv("merged_dataset_movement_5.csv")

# Target
y = df["MOVED"]

# Features
X = df.drop(columns=["MOVED"])

# Identify categorical vs numeric
categorical_cols = X.select_dtypes(include=["object"]).columns
numeric_cols = X.select_dtypes(include=["int64", "float64"]).columns

# Preprocessing
preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse=False), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)


# Naive Bayes model
model = Pipeline(steps=[
    ("preprocess", preprocess),
    ("nb", GaussianNB())
])

# 10-fold CV
kf = KFold(n_splits=10, shuffle=True, random_state=42)

y_pred = cross_val_predict(model, X, y, cv=kf)

# Accuracy
accuracy = accuracy_score(y, y_pred)
print("10-fold CV Accuracy:", accuracy)

# Confusion matrix
cm = confusion_matrix(y, y_pred)
print("Confusion Matrix:")
print(cm)

MemoryError: Unable to allocate 13.3 PiB for an array with shape (31086945, 60034924) and data type float64

In [10]:
import pandas as pd
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline

# Load data
df = pd.read_csv("merged_dataset_movement_5.csv")

# Drop high-cardinality columns
X = df.drop(columns=["MOVED", "COUNTYICP", "OCC"])

# Target
y = df["MOVED"]

# Identify categorical vs numeric
categorical_cols = X.select_dtypes(include=["object"]).columns
numeric_cols = X.select_dtypes(include=["int64", "float64"]).columns

# Preprocessing with OrdinalEncoder
preprocess = ColumnTransformer(
    transformers=[
        ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)

# Naive Bayes model
model = Pipeline(steps=[
    ("preprocess", preprocess),
    ("nb", GaussianNB())
])

# 10-fold CV
kf = KFold(n_splits=10, shuffle=True, random_state=42)

y_pred = cross_val_predict(model, X, y, cv=kf)

# Accuracy
accuracy = accuracy_score(y, y_pred)
print("10-fold CV Accuracy:", accuracy)

# Confusion matrix
cm = confusion_matrix(y, y_pred)
print("Confusion Matrix:")
print(cm)

ValueError: Input X contains NaN.
GaussianNB does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [1]:
import pandas as pd
df = pd.read_csv("merged_dataset_movement_5.csv")

In [3]:
cols = list(df.columns)
cols.remove("MOVED")
cols.append("MOVED")
df = df[cols]
df.to_csv("merged_dataset_movement_5_weka.csv", index=False)

In [4]:
df.columns[-1]

'MOVED'

In [5]:
# Rename headers for ease

rename_map = {
    "YEAR": "year",
    "SERIAL": "household_id",
    "PERNUM": "person_id",
    "NUMPREC": "num_persons_recorded",
    "NUMPERHH": "num_persons_household",
    "STATEFIP": "state",
    "CITY": "city_name",
    "URBAN": "urban_status",
    "COUNTYICP": "county_code",
    "COUNTYNHG": "county_nhg_code",
    "GQ": "group_quarters",
    "GQTYPE": "gq_type",
    "GQTYPED": "gq_type_detail",
    "SEX": "sex",
    "AGE": "age",
    "RACE": "race",
    "RACED": "race_detail",
    "BPL": "birthplace",
    "BPLD": "birthplace_detail",
    "BLIND": "blind",
    "DEAF": "deaf",
    "INSANE": "insane",
    "RELATE": "relationship",
    "RELATED": "relationship_detail",
    "MARST": "marital_status",
    "OCC": "occupation_code",
    "OCC1950": "occupation_1950",
    "HISTID": "hist_id",
    "HISTID_MOM2": "hist_id_mother",
    "HISTID_POP2": "hist_id_father",
    "SPLITHID": "split_household_id",
    "LINK1850": "link_1850",
    "SICKNESS": "sickness",
    "MOVED": "moved"
}

df = df.rename(columns=rename_map)

In [6]:
print(df)

          year  household_id  num_persons_recorded  num_persons_household  \
0         1860             1                     6                      6
1         1860             1                     6                      6
2         1860             1                     6                      6
3         1860             1                     6                      6
4         1860             3                     8                      8
...        ...           ...                   ...                    ...
34541046  1870       7766304                     7                      7
34541047  1870       7766433                     1                      1
34541048  1870       7766499                     9                      9
34541049  1870       7766509                     4                      4
34541050  1870       7766523                     5                      5

          state  city_name  urban_status  group_quarters  split_household_id  \
0             1          0             1               1                   1
1             1          0             1               1                   1
2             1          0             1               1                   1
3             1          0             1               1                   1
4             1          0             1               1                   3
...         ...        ...           ...             ...                 ...
34541046     56          0             1               1                1705
34541047     56          0             1               1                1834
34541048     56          0             1               2                1900
34541049     56          0             1               1                1910
34541050     56          0             1               1                1924

          person_id  ...  hist_id_mother  hist_id_father  STATEICP  \
0                 1  ...             NaN             NaN       NaN
1                 2  ...             NaN             NaN       NaN
2                 3  ...             NaN             NaN       NaN
3                 6  ...             NaN             NaN       NaN
4                 1  ...             NaN             NaN       NaN
...             ...  ...             ...             ...       ...
34541046          2  ...             NaN             NaN      68.0
34541047          1  ...             NaN             NaN      68.0
34541048          7  ...             NaN             NaN      68.0
34541049          1  ...             NaN             NaN      68.0
34541050          1  ...             NaN             NaN      68.0

          county_code  county_nhg_code  gq_type  gq_type_detail  sickness  \
0                 NaN              NaN      NaN             NaN         0
1                 NaN              NaN      NaN             NaN         0
2                 NaN              NaN      NaN             NaN         0
3                 NaN              NaN      NaN             NaN         0
4                 NaN              NaN      NaN             NaN         0
...               ...              ...      ...             ...       ...
34541046        370.0        5650115.0      0.0             0.0         0
34541047        370.0        5650115.0      0.0             0.0         0
34541048        370.0        5650115.0      0.0             0.0         0
34541049        410.0        5650135.0      0.0             0.0         0
34541050        410.0        5650135.0      0.0             0.0         0

          link_1850  moved
0               NaN      1
1               NaN      0
2               NaN      1
3               NaN      0
4               NaN      0
...             ...    ...
34541046        1.0      1
34541047        1.0      1
34541048        1.0      1
34541049        1.0      1
34541050        1.0      1

[34541051 rows x 107 columns]

In [7]:
# Dropping columns that are just creating noise and will not effect the model

drop_cols = [
    # Identifiers
    "household_id", "person_id", "hist_id", "hist_id_mother",
    "hist_id_father", "split_household_id", "link_1850",

    # High-cardinality geography
    "state", "city_name", "county_code", "county_nhg_code",

    # Relationship variables
    "relationship", "relationship_detail",

    # Occupation variables
    "occupation_code", "occupation_1950",

    # Group quarters details
    "gq_type", "gq_type_detail",

    # Birthplace detail
    "birthplace_detail",

    # Race detail
    "race_detail",

    # Household size variables
    "num_persons_recorded", "num_persons_household"
]

df_simplified = df.rename(columns=rename_map).drop(columns=drop_cols, errors="ignore")

In [8]:
print(df)

          year  household_id  num_persons_recorded  num_persons_household  \
0         1860             1                     6                      6
1         1860             1                     6                      6
2         1860             1                     6                      6
3         1860             1                     6                      6
4         1860             3                     8                      8
...        ...           ...                   ...                    ...
34541046  1870       7766304                     7                      7
34541047  1870       7766433                     1                      1
34541048  1870       7766499                     9                      9
34541049  1870       7766509                     4                      4
34541050  1870       7766523                     5                      5

          state  city_name  urban_status  group_quarters  split_household_id  \
0             1          0             1               1                   1
1             1          0             1               1                   1
2             1          0             1               1                   1
3             1          0             1               1                   1
4             1          0             1               1                   3
...         ...        ...           ...             ...                 ...
34541046     56          0             1               1                1705
34541047     56          0             1               1                1834
34541048     56          0             1               2                1900
34541049     56          0             1               1                1910
34541050     56          0             1               1                1924

          person_id  ...  hist_id_mother  hist_id_father  STATEICP  \
0                 1  ...             NaN             NaN       NaN
1                 2  ...             NaN             NaN       NaN
2                 3  ...             NaN             NaN       NaN
3                 6  ...             NaN             NaN       NaN
4                 1  ...             NaN             NaN       NaN
...             ...  ...             ...             ...       ...
34541046          2  ...             NaN             NaN      68.0
34541047          1  ...             NaN             NaN      68.0
34541048          7  ...             NaN             NaN      68.0
34541049          1  ...             NaN             NaN      68.0
34541050          1  ...             NaN             NaN      68.0

          county_code  county_nhg_code  gq_type  gq_type_detail  sickness  \
0                 NaN              NaN      NaN             NaN         0
1                 NaN              NaN      NaN             NaN         0
2                 NaN              NaN      NaN             NaN         0
3                 NaN              NaN      NaN             NaN         0
4                 NaN              NaN      NaN             NaN         0
...               ...              ...      ...             ...       ...
34541046        370.0        5650115.0      0.0             0.0         0
34541047        370.0        5650115.0      0.0             0.0         0
34541048        370.0        5650115.0      0.0             0.0         0
34541049        410.0        5650135.0      0.0             0.0         0
34541050        410.0        5650135.0      0.0             0.0         0

          link_1850  moved
0               NaN      1
1               NaN      0
2               NaN      1
3               NaN      0
4               NaN      0
...             ...    ...
34541046        1.0      1
34541047        1.0      1
34541048        1.0      1
34541049        1.0      1
34541050        1.0      1

[34541051 rows x 107 columns]

In [9]:
# Simplify sex into binary: male = 1, female = 0
df_simplified["sex_binary"] = df_simplified["sex"].apply(lambda x: 1 if x == 1 else 0)

In [10]:
# bianirized sex values totals
df_simplified["sex_binary"].value_counts()

1    18555297
0    15985754
Name: sex_binary, dtype: int64

In [12]:
# simplifiying race categories 

def simplify_race(x):
    if x == 1:
        return "White"
    elif x == 2:
        return "Black"
    elif x == 3:
        return "Native"
    else:
        return "Other"

df_simplified["race_group"] = df_simplified["race"].apply(simplify_race)

In [13]:
df_simplified["race_group"].unique()

array(['White', 'Native', 'Black', 'Other'], dtype=object)

In [14]:
df_simplified["race_group"].value_counts()

White     34139772
Black       397914
Native        3040
Other          325
Name: race_group, dtype: int64

In [15]:
df_simplified["race_group"].value_counts(normalize=True)

White     0.988383
Black     0.011520
Native    0.000088
Other     0.000009
Name: race_group, dtype: float64

In [16]:
# US born or foreign born

def simplify_birthplace(x):
    if pd.isna(x):
        return "Unknown"
    elif x <= 56:
        return "US"
    else:
        return "Foreign"

df_simplified["birthplace_group"] = df_simplified["birthplace"].apply(simplify_birthplace)

In [17]:
df_simplified["birthplace_group"].unique()

array(['US', 'Foreign', 'Unknown'], dtype=object)

In [18]:
df_simplified["birthplace_group"].value_counts()

US         19384853
Unknown    12898748
Foreign     2257450
Name: birthplace_group, dtype: int64

In [19]:
# Simplifying marriage status

def simplify_marital_status(x):
    if x == 1:
        return 1   # married
    else:
        return 0   # not married

df_simplified["marital_binary"] = df_simplified["marital_status"].apply(simplify_marital_status)

KeyError: 'marital_status'

In [20]:
[col for col in df.columns if "MAR" in col.upper()]

[]

In [21]:
def simplify_occupation(x):
    if pd.isna(x):
        return "Unknown"
    elif 0 <= x <= 99:
        return 1   # agricultural
    else:
        return 0   # non-agricultural

df_simplified["occupation_binary"] = df_simplified["occupation_code"].apply(simplify_occupation)

KeyError: 'occupation_code'

In [22]:
print(df)

          year  household_id  num_persons_recorded  num_persons_household  \
0         1860             1                     6                      6
1         1860             1                     6                      6
2         1860             1                     6                      6
3         1860             1                     6                      6
4         1860             3                     8                      8
...        ...           ...                   ...                    ...
34541046  1870       7766304                     7                      7
34541047  1870       7766433                     1                      1
34541048  1870       7766499                     9                      9
34541049  1870       7766509                     4                      4
34541050  1870       7766523                     5                      5

          state  city_name  urban_status  group_quarters  split_household_id  \
0             1          0             1               1                   1
1             1          0             1               1                   1
2             1          0             1               1                   1
3             1          0             1               1                   1
4             1          0             1               1                   3
...         ...        ...           ...             ...                 ...
34541046     56          0             1               1                1705
34541047     56          0             1               1                1834
34541048     56          0             1               2                1900
34541049     56          0             1               1                1910
34541050     56          0             1               1                1924

          person_id  ...  hist_id_mother  hist_id_father  STATEICP  \
0                 1  ...             NaN             NaN       NaN
1                 2  ...             NaN             NaN       NaN
2                 3  ...             NaN             NaN       NaN
3                 6  ...             NaN             NaN       NaN
4                 1  ...             NaN             NaN       NaN
...             ...  ...             ...             ...       ...
34541046          2  ...             NaN             NaN      68.0
34541047          1  ...             NaN             NaN      68.0
34541048          7  ...             NaN             NaN      68.0
34541049          1  ...             NaN             NaN      68.0
34541050          1  ...             NaN             NaN      68.0

          county_code  county_nhg_code  gq_type  gq_type_detail  sickness  \
0                 NaN              NaN      NaN             NaN         0
1                 NaN              NaN      NaN             NaN         0
2                 NaN              NaN      NaN             NaN         0
3                 NaN              NaN      NaN             NaN         0
4                 NaN              NaN      NaN             NaN         0
...               ...              ...      ...             ...       ...
34541046        370.0        5650115.0      0.0             0.0         0
34541047        370.0        5650115.0      0.0             0.0         0
34541048        370.0        5650115.0      0.0             0.0         0
34541049        410.0        5650135.0      0.0             0.0         0
34541050        410.0        5650135.0      0.0             0.0         0

          link_1850  moved
0               NaN      1
1               NaN      0
2               NaN      1
3               NaN      0
4               NaN      0
...             ...    ...
34541046        1.0      1
34541047        1.0      1
34541048        1.0      1
34541049        1.0      1
34541050        1.0      1

[34541051 rows x 107 columns]

In [23]:
for col in df_simplified.columns:
    print(col)

year
urban_status
group_quarters
sex
age
race
birthplace
NATIVITY
LIT
VERSIONHIST
blind
deaf
IDIOTIC
insane
HIK
LINK1860
LINK1870
LINK1880
VERSIONHIK
PERNUM_MOM
PERNUM_POP
PERNUM_MOM2
PERNUM_POP2
SEX_MOM
SEX_POP
SEX_MOM2
SEX_POP2
AGE_MOM
AGE_POP
AGE_MOM2
AGE_POP2
RACE_MOM
RACE_POP
RACE_MOM2
RACE_POP2
RACED_MOM
RACED_POP
RACED_MOM2
RACED_POP2
BPL_MOM
BPL_POP
BPL_MOM2
BPL_POP2
BPLD_MOM
BPLD_POP
BPLD_MOM2
BPLD_POP2
NATIVITY_MOM
NATIVITY_POP
NATIVITY_MOM2
NATIVITY_POP2
LIT_MOM
LIT_POP
LIT_MOM2
LIT_POP2
OCC_MOM
OCC_POP
OCC_MOM2
OCC_POP2
OCC1950_MOM
OCC1950_POP
OCC1950_MOM2
OCC1950_POP2
VERSIONHIST_MOM
VERSIONHIST_POP
VERSIONHIST_MOM2
VERSIONHIST_POP2
BLIND_MOM
BLIND_POP
BLIND_MOM2
BLIND_POP2
DEAF_MOM
DEAF_POP
DEAF_MOM2
DEAF_POP2
IDIOTIC_MOM
IDIOTIC_POP
IDIOTIC_MOM2
IDIOTIC_POP2
INSANE_MOM
INSANE_POP
INSANE_MOM2
INSANE_POP2
HISTID_MOM
HISTID_POP
STATEICP
sickness
moved
sex_binary
race_group
birthplace_group

In [27]:
keep_cols = [
    "year",
    "urban_status",
    "group_quarters",
    "sex",
    "age",
    "race",
    "birthplace",
    "sickness",
    "moved",
    
    # simplified variables
    "sex_binary",
    "race_group",
    "birthplace_group",
    
    # disability variables
    "blind",
    "deaf",
    "IDIOTIC",
    "insane"
]

In [28]:
df_simplified = df_simplified[keep_cols]

In [29]:
for col in df_simplified.columns:
    print(col)

year
urban_status
group_quarters
sex
age
race
birthplace
sickness
moved
sex_binary
race_group
birthplace_group
blind
deaf
IDIOTIC
insane

In [30]:
# create age ranges

def age_range(x):
    if pd.isna(x):
        return "Unknown"
    elif x <= 14:
        return "0_14"
    elif x <= 24:
        return "15_24"
    elif x <= 44:
        return "25_44"
    elif x <= 64:
        return "45_64"
    else:
        return "65_plus"

df_simplified["age_group"] = df_simplified["age"].apply(age_range)

/tmp/ipykernel_1550/1977949870.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_simplified["age_group"] = df_simplified["age"].apply(age_range)

In [31]:
df_simplified = df_simplified.copy()

In [32]:
df_simplified["age_group"] = df_simplified["age"].apply(age_range)

In [33]:
df_simplified["age_group"].unique()
df_simplified["age_group"].value_counts()

0_14       11976662
25_44       9584280
15_24       6766168
45_64       5190410
65_plus     1023531
Name: age_group, dtype: int64

In [34]:
df_simplified["urban_status"].unique()

array([1, 2])

In [35]:
df_simplified["urban_status"].value_counts()

1    28264312
2     6276739
Name: urban_status, dtype: int64

In [36]:
df_simplified["group_quarters"].unique()

array([1, 2, 4, 3])

In [37]:
# creating bianary classification for group quarters 

def simplify_gq(x):
    if pd.isna(x):
        return "Unknown"
    elif x == 1:
        return 0   # household / non-institutional
    else:
        return 1   # institutional or group quarters

df_simplified["gq_binary"] = df_simplified["group_quarters"].apply(simplify_gq)

In [38]:
df_simplified["gq_binary"].unique()
df_simplified["gq_binary"].value_counts()

0    33091436
1     1449615
Name: gq_binary, dtype: int64

In [41]:
df_simplified["sickness"].unique()
df_simplified["sickness"].value_counts()

0    34541051
Name: sickness, dtype: int64

In [42]:
# dropping sickness since it contains no value

df_simplified = df_simplified.drop(columns=["sickness"])

In [43]:
df_simplified["moved"].unique()

array([1, 0])

In [44]:
df_simplified["moved"].value_counts()

0    18127569
1    16413482
Name: moved, dtype: int64

In [45]:
# reodering the columns for WEKA

new_order = [
    "year",
    "sex_binary",
    "age_group",
    "race_group",
    "birthplace_group",
    "urban_status",
    "gq_binary",
    "blind",
    "deaf",
    "IDIOTIC",
    "insane",
    "moved"
]

df_simplified = df_simplified[new_order]

In [46]:
df_simplified.columns.tolist()

['year',
 'sex_binary',
 'age_group',
 'race_group',
 'birthplace_group',
 'urban_status',
 'gq_binary',
 'blind',
 'deaf',
 'IDIOTIC',
 'insane',
 'moved']

In [47]:
# create the new csv for know dis

df_simplified.to_csv("know_disc_assign2.csv", index=False)

In [48]:
import pandas as pd

df_check = pd.read_csv("know_disc_assign2.csv")

In [49]:
df_check.head()

,year,sex_binary,age_group,race_group,birthplace_group,urban_status,gq_binary,blind,deaf,IDIOTIC,insane,moved
0,1860,1,25_44,White,US,1,0,0,0,0,0,1
1,1860,0,25_44,White,US,1,0,0,0,0,0,0
2,1860,0,0_14,White,US,1,0,0,0,0,0,1
3,1860,0,0_14,White,US,1,0,0,0,0,0,0
4,1860,1,45_64,White,US,1,0,0,0,0,0,0

In [50]:
df_check.columns.tolist()

['year',
 'sex_binary',
 'age_group',
 'race_group',
 'birthplace_group',
 'urban_status',
 'gq_binary',
 'blind',
 'deaf',
 'IDIOTIC',
 'insane',
 'moved']

In [51]:
len(df_check)

34541051

In [52]:
df_check["age_group"].value_counts()

0_14       11976662
25_44       9584280
15_24       6766168
45_64       5190410
65_plus     1023531
Name: age_group, dtype: int64

In [53]:
df_check["moved"].value_counts()

0    18127569
1    16413482
Name: moved, dtype: int64

In [54]:
df_check[["blind","deaf","IDIOTIC","insane"]].sum()

blind      14846
deaf       17890
IDIOTIC    23475
insane     16482
dtype: int64

In [55]:
df_check.dtypes

year                 int64
sex_binary           int64
age_group           object
race_group          object
birthplace_group    object
urban_status         int64
gq_binary            int64
blind                int64
deaf                 int64
IDIOTIC              int64
insane               int64
moved                int64
dtype: object